version: '3.8'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver_roi
    restart: always
    cap_add:
    - SYS_PTRACE
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=byPass123!@
      - MSSQL_PID=Developer
      - MSSQL_USER=sa
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./micro-dashboard-roi
      dockerfile: Dockerfile
    container_name: api_roi
    depends_on:
      - db
    ports:
      - "5078:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=db;Database=micro-dashboardDB;User Id=sa;Password=byPass123!@;TrustServerCertificate=True;Integrated Security=False;"
      - ASPNETCORE_URLS=http://+:8080

volumes:
  sql_data: