// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using micro_dashboard_roi.Data;

#nullable disable

namespace micro_dashboard_roi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("micro_dashboard_roi.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_campanha");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_produto");

                    b.HasKey("Id");

                    b.ToTable("tb_campanhas", (string)null);
                });

            modelBuilder.Entity("micro_dashboard_roi.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_lancamento")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("receita");

                    b.Property<decimal>("Spend")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gasto");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("tb_lancamentos", (string)null);
                });

            modelBuilder.Entity("micro_dashboard_roi.Models.DailyLog", b =>
                {
                    b.HasOne("micro_dashboard_roi.Models.Campaign", "Campaign")
                        .WithMany("Logs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("micro_dashboard_roi.Models.Campaign", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
